import { z } from "zod";

import { playgroupKeySchema } from "../playgroups";
import { birthdayStringSchema, partialDateStringSchema } from "../types";

export const ferretSchema = z.object({
  name: z.string(),
  wikipage: z.string(),
  aliases: z.array(z.string()).readonly(),
  commands: z.array(z.string()).readonly(),
  sex: z.literal(["Male", "Female"]).nullable(),
  birth: partialDateStringSchema.nullable(),
  birthday: birthdayStringSchema.nullable().optional(),
  arrival: partialDateStringSchema.nullable(),
  valhalla: partialDateStringSchema.nullable(),
  playgroup: playgroupKeySchema,
  summary: z.string().optional(),
  lore: z.string().optional(),
  clips: z
    .array(
      z.object({
        url: z.string(),
        caption: z.string(),
      }),
    )
    .readonly(),
  merch: z
    .union([
      z.object({
        plushie: z.string(),
      }),
      z.object({
        other: z.string(),
      }),
    ])
    .nullable()
    .optional(),
});

export type Ferret = z.infer<typeof ferretSchema>;

const ferrets = {
  ash: {
    name: "Ash",
    wikipage: "Ash",
    aliases: [],
    commands: ["ash"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-12-01",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Ash is a rescue ferret of Snails House. Ash came to the rescue with [[Rowan]], [[Juniper]] and [[Rye]].",
    lore: "Ash came with [[Rowan]], [[Juniper]] and [[Rye]] from a very loving home in which life circumstances had unfortunately changed, so they came to Snails House.",
    clips: [],
    merch: null,
  },
  badger: {
    name: "Badger",
    wikipage: "Badger",
    aliases: [],
    commands: ["badger"],
    sex: "Male",
    birth: null,
    birthday: "02-26",
    arrival: "2024-02-26",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Badger is a rescue ferret of Snails House. He typically enjoys playing in the toobs and rice bin. His favorite playmate is [[Peepo]].",
    lore: "Badger is a part of the 5 ferrets who were found abandoned in an unlocked shed by the Humane Society. They then reached out to the rescue for assistance. Badger came to the rescue with [[Moose]], [[Peepo]], [[Pepper]], and [[Salt]]. He is known in chat to be a cute cranky grandpa.",
    clips: [],
    merch: null,
  },
  bagel: {
    name: "Bagel",
    wikipage: "Bagel",
    aliases: [],
    commands: ["bagel"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-03-09",
    valhalla: "2025-05-09",
    playgroup: "valhalla",
    summary:
      "Bagel was a rescue ferret of Snails House. She enjoyed the company of [[Peanut 2]], but she did not care much for the young males of the business.",
    lore: "Bagel came to the rescue together with [[Peanut 2]]. They were surrendered by loving owners due to age and existing health conditions.",
    clips: [],
    merch: null,
  },
  banana: {
    name: "Banana",
    wikipage: "Banana",
    aliases: ["Nana"],
    commands: ["banana"],
    sex: "Female",
    birth: null,
    birthday: "04-22",
    arrival: "2023-07-07",
    valhalla: "2025-08-09",
    playgroup: "valhalla",
    summary:
      "Banana was a rescue ferret of Snails House. She enjoyed good supervised outdoor time, and she really enjoyed snuggling with [[Zero]] and [[Eddie]]. She had a crooked/lightning shaped tail.",
    lore: `Banana was picked up after a facebook user posted about not being able to care for the ferret any more after her buddy passed awa. They got in contact with them and picked her up not to long after.

Banana's birthday was confirmed when owner sent over paperwork to Shaye.`,
    clips: [],
    merch: null,
  },
  bandit: {
    name: "Bandit",
    wikipage: "Bandit",
    aliases: ["Chicken leg, nekkid boi, skinboy, hotdog"],
    commands: ["bandit"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-01-05",
    valhalla: "2024-04-05",
    playgroup: "valhalla",
    summary:
      "Bandit was a rescue ferret of Snails House. He came to the rescue with advanced medical issues, but he enjoyed making new friends while going through treatment.",
    lore: `Bandit came to the rescue with his friend [[Moxie]]. Bandit was rescued while he already was in the advanced stages of adrenal . Being mostly bald across his entire body, he still had a good time with his new friends. He loved to cruise through the tubes or be eaten by a crocodile.

After about five months in the care of Shaye and Thor, he sadly passed away of old age.`,
    clips: [],
    merch: null,
  },
  beans: {
    name: "Beans",
    wikipage: "Beans",
    aliases: [
      "Beanus Weenus",
      "Bean Boy",
      "Mr. Bean",
      "Jelly Bean",
      "Beanie Baby",
      "Beansman",
      "Unrepentant Ear Criminal",
    ],
    commands: ["beans", "bean"],
    sex: "Male",
    birth: "2021-12-19",
    birthday: "12-19",
    arrival: "2022-04-01",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Beans is a ferret of Snails House. He is known for being very photogenic and causing chaos. He is famous for many reasons, one of which is his likeness as a plushie!",
    lore: `As one of the original ferrets before Snails House became a sanctuary, Beans came from a pet store. Thor and Shaye saw him alone in his enclosure and decided to bring him home to have friends, especially since ferrets are very social animals.

Beans' birthday is December 19th, 2021. He also has a sweet tooth and craves Shaye's ice cream. Since the day he came home, he has held the number one spot in Zultralord's heart. 

Due to Beans being such a chill dude, aside from ear crimes, he and [[Chili]] are typically part of the welcome committee to introduce new ferrets to the business when they are ready to integrate.

During the first night in his temporary cage (quarantine), he proceeded to rip one of the bars off and escape. He started running around and doing a lot of dooking because he was very excited. He was running into the room where Thor was sleeping and woke him up. Because of the Meme Beans in Places they shouldn't be in they named him Beans.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Beans typed "Dr" and "Bpq".`,
    clips: [],
    merch: {
      plushie: "https://merch.piratesoftware.live/products/beans-plush",
    },
  },
  beef: {
    name: "Beef",
    wikipage: "Beef",
    aliases: ["The Thief"],
    commands: ["beef"],
    sex: "Male",
    birth: "2021-02-20",
    birthday: "02-20",
    arrival: "2021-07-02",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Beef is a ferret of Snails House. He enjoys stealing food from other ferrets' mouths and desires the freshest of water from the bottom of the water bowl.  [[Cheese]] is his sister.",
    lore: "Originally a pet of Thor and Shaye, Beef came to Snails House from the pet store with his sister [[Cheese]]. He has quite the personality. He will stick his head into the water dish, all the way to the bottom and then panic, as if he's drowning. Beef used to be very interested in [[Mouse]], but she was indifferent. He enjoys playing with [[Pepper]] when given the opportunity, but they are currently in different play groups. Beef now currently resides in the oldies cage so that he and his sister's aging health can be monitored closely.",
    clips: [],
    merch: null,
  },
  bigmike: {
    name: "Big Mike",
    wikipage: "Big_Mike",
    aliases: [],
    commands: ["bigmike"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-02-25",
    valhalla: null,
    playgroup: "m",
    summary:
      "Big Mike is a rescue ferret of Snails House. He was super ill when he first joined the sanctuary, but has since recovered. He is a big boy with big white paws!",
    lore: `Big Mike was surrendered to Snails House by a pet store due to having Covid, Influenza-A, and Influenza-B. Thanks to the rescue's knowledge and resources, he was able to recover. Now that he's feeling better, his big goober side has really started to show. After his treatment and quarantine, Mike played with the oldies at first since they treated him gently. Once he was feeling more confident, he started a new playgroup with his new friend [[Maisy]] to form M&M, which quickly included [[Milo]] and formed M3.

When looking to identify him, Mike is a big boy with the total white paw chrome package (that means all four feet)! He loves to play chase and especially enjoys playing with his buddy [[Milo]]. Mike also enjoys mingling with many different ferrets and playgroups, so be sure to keep an eye out for him.`,
    clips: [],
    merch: null,
  },
  bruce: {
    name: "Bruce",
    wikipage: "Bruce",
    aliases: [],
    commands: ["bruce"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-03-30",
    valhalla: null,
    playgroup: "rb",
    summary:
      "Bruce is a rescue ferret of Snails House. He's a very chill and laid back dude who sometimes activates and crushes castles while wardancing. He enjoys leisure walks with his friend [[Teep]].",
    lore: "Bruce came to the rescue with [[Teep]] from a loving home. They were surrendered because they needed senior care in which the rescue could provide. After some time, and due to his very unshakable and calm demeanor, he made friends and was paired with [[Rusty]] to form R&B.",
    clips: [],
    merch: null,
  },
  bubbles: {
    name: "Bubbles",
    wikipage: "Bubbles",
    aliases: [],
    commands: ["bubbles", "bubble"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary: "Bubbles is a rescue ferret of Snail's House.",
    lore: "Bubbles is a rescue ferret of Snail's House, she came to the rescue in February 2026. Her birthday is confirmed to be in July.",
    clips: [],
    merch: null,
  },
  calypso: {
    name: "Calypso",
    wikipage: "Calypso",
    aliases: [],
    commands: ["calypso"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Calypso is a rescue ferret of Snail's House. Calypso came to the rescue with Evander and Hector.",
    lore: "Calypso is a rescue ferret of Snail's House. Calypso came to the rescue in February 2026 with Evander and Hector. They came to the rescue to hopefully be friends with Nemo, which they love playtime together and became NES: Nemo entertainment system.",
    clips: [],
    merch: null,
  },
  cashew: {
    name: "Cashew",
    wikipage: "Cashew",
    aliases: ["Cash, Speedy Muscle Boy"],
    commands: ["cashew"],
    sex: "Male",
    birth: "2024-04-13",
    birthday: "04-13",
    arrival: "2024-08-03",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Cashew is a rescue ferret of Snails House. While he plays well with everyone, he really enjoys playing with [[Pickle]]. He is easy to identify during playtime by his large size and nub tail.",
    lore: `Cashew was adopted from the pet store with [[Hazelnut]] and [[Peanut]] as part of the "Nut Gang". Peanut and Hazel were rescued due to them having Waardenburg Syndrome  and multiple behavioral issues. Cashew developed "problematic" behavioral issues due to living with cage mates which had also bonded to him. These days, he really enjoys playtime with the general population playgroup.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Cashew typed "K", "Km", "E4", "Me", and "Cash".`,
    clips: [],
    merch: null,
  },
  cheese: {
    name: "Cheese",
    wikipage: "Cheese",
    aliases: ["The Final Boss"],
    commands: ["cheese"],
    sex: "Female",
    birth: "2021-02-20",
    birthday: "02-20",
    arrival: "2021-07-02",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Cheese is a ferret of Snails House. She is the professional photo model for the business and loves posing for the camera. She enjoys redecorating the playroom and climbing Shaye.",
    lore: 'Cheese came from the pet store with her brother [[Beef]]. They were both bought as pets before Thor and Shaye decided to start a ferret sanctuary. Cheese is a Roan/Silver ferret. With each shed, she may get more and more white hair, (called "roaning out"), and will probably be fully white eventually. Cheese is a very sweet little lady who likes to chill and cuddle. She is mostly left alone by the rowdy youngins\' because she is actually the most vicious fighter of the business. She is incredibly photogenic. Recently, she moved from general population to live with the oldies with her brother, [[Beef]], so that her health could be monitored more closely.',
    clips: [],
    merch: null,
  },
  chili: {
    name: "Chili",
    wikipage: "Chili",
    aliases: ["Mandarin", "Heavy Weight Champion of the World, Trashmaster"],
    commands: ["chili"],
    sex: "Male",
    birth: null,
    birthday: "01-10",
    arrival: "2024-01-11",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Chili is a rescue ferret of Snails House. He has an affinity for climbing, gym workouts, and a strange obsession with trash cans. He currently holds the title of heaviest recorded ferret of the rescue at around 1960 grams.",
    lore: `Chili came to the rescue with his fellow housemate [[Fig]]. He enjoys climbing often, and frequently finds himself in the trashcan of the playroom, (as seen below), due to these shenanigans. 

Due to Chili being such a chill dude, he and [[Beans]] are typically part of the welcome committee to introduce new ferrets to the business when they are ready to integrate.`,
    clips: [],
    merch: null,
  },
  cowboy: {
    name: "Cowboy",
    wikipage: "Cowboy",
    aliases: ["The Dude, Cowbaby"],
    commands: ["cowboy"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-08-25",
    valhalla: "2025-08-19",
    playgroup: "valhalla",
    summary:
      "Cowboy was a rescue ferret of Snails House. He was known to have furry chaps. Despite his hairlessness, he refused to wear the sweaters Shaye gave him. Instead, he loved to cuddle in blankets, preferably by himself.",
    lore: "Cowboy was an older ferret [who was surrendered by a pig rescue] to Snails House with advanced adrenal disease.  He barely had hair remaining, but he still had some action in him.",
    clips: [],
    merch: null,
  },
  darunia: {
    name: "Darunia",
    wikipage: "Darunia",
    aliases: [],
    commands: ["darunia"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Darunia is a ferret of Snails House.",
    lore: "Darunia joined the rescue with [[Nabooru]], [[Zelda]], [[Saria]], [[Ruto]], [[Impa]], and [[Rauru]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  demeter: {
    name: "Demeter",
    wikipage: "Demeter",
    aliases: ["Professional Noseball Noodle, Deme"],
    commands: ["demeter"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-06-16",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Demeter is a rescue ferret of Snails House. She is a classic ferret who truly enjoys the sport of noseball, and is the fastest of the business. Joining [[Chili]], she also has a strange obsession with trash cans.",
    lore: `Demeter joined the rescue together with [[Mistoffelees]]. They were surrendered from a loving home because the owners felt they could no longer provide adequate care. She is often seen running around the playroom at full speed with a ball at her nose, playing with the other ferrets of general population, and sometimes even attempting clever escapes.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Demeter typed "G" and "li8s".`,
    clips: [],
    merch: null,
  },
  eddie: {
    name: "Eddie",
    wikipage: "Eddie",
    aliases: [],
    commands: ["eddie"],
    sex: "Male",
    birth: "2017-12-16",
    birthday: "12-16",
    arrival: "2023-08-18",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Eddie is a rescue ferret of Snails House. He came into the rescue as a solo ferret. Since he is so chill, he meshed really well with the oldies, and enjoys snuggling with [[Zero]] and [[Banana]].",
    lore: "Eddie came to the rescue from a pair of fantastic owners. His lifelong buddy died, and he needed other ferret friends because they are super social creatures.  Now he enjoys his leisure time among the oldies with lots of jaunts around the playroom, plenty of Mango snuggles, and tasty soupies.",
    clips: [],
    merch: null,
  },
  enoki: {
    name: "Enoki",
    wikipage: "Enoki",
    aliases: ["Kiki"],
    commands: ["enoki"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-10-25",
    valhalla: null,
    playgroup: "k",
    summary: "Enoki is a ferret of Snails House.",
    lore: `She joined together with [[Nameko]]. Her name is sourced from a kind of Mushroom. 

She is a sassy old lady and dooks alot.`,
    clips: [],
    merch: null,
  },
  evander: {
    name: "Evander",
    wikipage: "Evander",
    aliases: [],
    commands: ["evander"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Evander is a rescue ferret of Snail's House. Evander came to the rescue with Calypso and Hector.",
    lore: "Evander is a rescue ferret of Snail's House. Evander came to the rescue in February 2026 with Calypso and Hector. They came to the rescue to hopefully be friends with Nemo, which they love playtime together and became NES: Nemo entertainment system.",
    clips: [],
    merch: null,
  },
  felix: {
    name: "Felix",
    wikipage: "Felix",
    aliases: ["Former nudist ferret"],
    commands: ["felix"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-05-23",
    valhalla: "2024-09-17",
    playgroup: "valhalla",
    summary: "Felix was a rescue ferret of Snails House.",
    lore: "Felix joined us as a nekkid ferret and had a lot of fun with both [[Finn]] and his new friends. They were in-state medical surrenders. Sadly, his age and illness caught up with him. He passed with his best friend Finn by his side. Link",
    clips: [],
    merch: null,
  },
  fig: {
    name: "Fig",
    wikipage: "Fig",
    aliases: ["Spiller of Soops"],
    commands: ["fig"],
    sex: "Male",
    birth: null,
    birthday: "01-10",
    arrival: "2024-01-11",
    valhalla: "2025-07-21",
    playgroup: "valhalla",
    summary:
      "Fig was a rescue ferret of Snails House. While he loved snuggling with the oldies, he was a great babysitter for [[Henry]]. He was easy to identify due to his balding tail.",
    lore: "Fig came to the rescue with his fellow housemate [[Chili]]. Figs birthday is January 10th.",
    clips: [],
    merch: null,
  },
  finch: {
    name: "Finch",
    wikipage: "Finch",
    aliases: [],
    commands: ["finch"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-12-27",
    valhalla: null,
    playgroup: "fs",
    summary:
      "Finch is a rescue ferret of Snails House. He is a sweet old man who came to the rescue with his cagemate [[Stinky]].",
    lore: "Finch came to Snails House with his cagemate, [[Stinky]], as a medical surrender due to a cyst on his head. He is super sweet and enjoys cuddles.",
    clips: [],
    merch: null,
  },
  finn: {
    name: "Finn",
    wikipage: "Finn",
    aliases: ["Finnegan"],
    commands: ["finn"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-05-23",
    valhalla: "2025-12-22",
    playgroup: "valhalla",
    summary:
      "Finn is a rescue ferret of Snails House. While he sometimes struggles to make ferret friends, he really enjoys human snuggles and scritches. He came to the rescue with his friend [[Felix]].",
    lore: "Finn joined us together with his, at the time, naked friend [[Felix]]. They were in-state medical surrenders. For a while, the best way to identify Finn, was to see Felix with him. Finn was very protective of his best friend [[Felix]]. Finn was there when his best friend passed away. These days, Finn enjoys the solo life with his gaming buddy, Shaye.",
    clips: [],
    merch: null,
  },
  george: {
    name: "George",
    wikipage: "George",
    aliases: [],
    commands: ["george"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary:
      "George is a rescue ferret of Snail's House. He came to the rescue with Tucker.",
    lore: "George is a rescue ferret of Snail's House. George joined the rescue with his cagemate Tucker.",
    clips: [],
    merch: null,
  },
  ghost: {
    name: "Ghost",
    wikipage: "Ghost",
    aliases: ["Solo runner"],
    commands: ["ghost"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2023-05-06",
    valhalla: "2025-04-26",
    playgroup: "valhalla",
    summary:
      "Ghost was a rescue ferret of Snails House. She was one of the few solo play time ferrets who prefers the company of her human caretakers.",
    lore: `Ghost was rescued from a family, which sadly hadn't taken care of her properly, this caused her to be aggressive towards other animals. Shaye tried to integrate her a couple of times with other ferrets; unfortunately, without success. In the old house, she had a seperate cage in the same room as the other ferrets. In the new house she got her own cage in Shaye's office. To ensure she got enough interaction, she had solo playtime with either Shaye or Thor. It was revealed that Ghost's original name was Strawberry, it was changed as the name did not fit.

Thor explaining Ghost's situation in short: Link`,
    clips: [],
    merch: null,
  },
  hazelnut: {
    name: "Hazelnut",
    wikipage: "Hazelnut",
    aliases: ["Hazel", "Sock Tax Criminal"],
    commands: ["hazelnut"],
    sex: "Female",
    birth: "2024-04-13",
    birthday: "04-13",
    arrival: "2024-08-03",
    valhalla: null,
    playgroup: "genpop",
    summary:
      'Hazel is a rescue ferret of Snails House. She enjoys fighting the "ghosts" she sees in the hammocks, and she has an obsession with biting socks of her human caretakers. She has a mostly white coat and very energetic activity.',
    lore: `Hazelnut was adopted from a pet store with [[Cashew]] and [[Peanut]] as part of the "Nut Gang". She has Waardenburg Syndrome  , is fully deaf, and has many behavioral issues. She was sold and returned multiple times due to these behavioral issues before the rescue acquired her.

These days, Hazel can be seen bopping around playtime with her general population friends, chasing her caretakers around the playroom, and playing with the wand toys.`,
    clips: [],
    merch: null,
  },
  hector: {
    name: "Hector",
    wikipage: "Hector",
    aliases: [],
    commands: ["hector"],
    sex: null,
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Hector is a rescue ferret of Snail's House. Hector came to the rescue with Calypso and Evander.",
    lore: "Hector  is a rescue ferret of Snail's House. Hector came to the rescue in February 2026 with Evander and Calypso. They came to the rescue to hopefully be friends with Nemo, which they love playtime together and became NES: Nemo entertainment system",
    clips: [],
    merch: null,
  },
  henry: {
    name: "Henry",
    wikipage: "Henry",
    aliases: ["Henwy", "Nascar Driver, Son of Shaye, Henny, The King"],
    commands: ["henry"],
    sex: "Male",
    birth: null,
    birthday: "08-31",
    arrival: "2024-03-01",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Henry is a rescue ferret of Snails House. Very wobbly. He's professionally trained as a NASCAR driver.  Additionally, he enthusiastically enjoys soup, often making a good mess for his caretakers to clean up.",
    lore: "Henry is our special boy. He runs in circles, wiggles his head, and generally is the cutest. Henry was initially diagnosed with possible neurologic symptoms; this seemed to cause him to have very bad motor control and run in a circular motion. He only turned left, earning him the nickname: Nascar driver",
    clips: [],
    merch: null,
  },
  impa: {
    name: "Impa",
    wikipage: "Impa",
    aliases: [],
    commands: ["impa"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Impa is a ferret of Snails House.",
    lore: "Impa joined the rescue with [[Nabooru]], [[Darunia]], [[Saria]], [[Ruto]], [[Zelda]], and [[Rauru]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  jack: {
    name: "Jack",
    wikipage: "Jack",
    aliases: ["Captain Jack"],
    commands: ["jack"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-02-23",
    valhalla: "2026-02-03",
    playgroup: "valhalla",
    summary:
      "Jack is a rescue ferret of Snails House. He is a solo-play ferret who prefers to play by himself.",
    lore: `Jack joined the rescue as an oldie, (approximately 7-8 years old), due to blood sugar crash from insulinoma. He came from a loved rescue that also surrendered [[Kitty]] for similar reasons.

Jack was a Blaze ferret and roans out. Roaning out means that with each shed, he will get more white hair, but likely he may also keep some markings.`,
    clips: [],
    merch: null,
  },
  jasmine: {
    name: "Jasmine",
    wikipage: "Jasmine",
    aliases: ["Jazzy"],
    commands: ["jasmine"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-07-11",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Jasmine is a rescue ferret of Snails House. While she resides with the oldies, she has quite the get-up and go attitude! She is frequently seen promenading around the playroom during oldie playtime.",
    lore: "Jasmine arrived at the rescue as a solo lady from a loving home. She was in need of friends and some senior medical care that the rescue could provide. She is a super active old lady who seems to always want playtime. She likes chilling in the comfy beds. Occasionally, likes to play with the balls available around the playroom. And like any active old lady, she demands to be involved in ALL playtimes.",
    clips: [],
    merch: null,
  },
  jinx: {
    name: "Jinx",
    wikipage: "Jinx",
    aliases: ["Chill Climber"],
    commands: ["jinx"],
    sex: "Female",
    birth: null,
    birthday: "09-30",
    arrival: "2024-03-01",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Jinx is a rescue ferret of Snails House. She is a very playful girl who gets along with many of business. She is also a professional escape artist with a knowledge of both directions: up AND down!",
    lore: `Jinx came to the rescue together with [[Henry]]. They are in different playgroups because of Henry requiring special treatment. Jinx is quite playful and gets along well with the other ferrets. Recently, Jinx joined the crew of escape artists.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Jinx typed "2a 😅".`,
    clips: [],
    merch: null,
  },
  juniper: {
    name: "Juniper",
    wikipage: "Juniper",
    aliases: [],
    commands: ["juniper"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-12-01",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Juniper is a rescue ferret of Snails House. Juniper came to the rescue with [[Ash]], [[Rowan]] and [[Rye]].",
    lore: "Juniper came with [[Ash]], [[Rowan]] and [[Rye]] from a very loving home in which life circumstances had unfortunately changed, so they came to Snails House.",
    clips: [],
    merch: null,
  },
  kahlua: {
    name: "Kahlua",
    wikipage: "Kahlua",
    aliases: ["Ear Crime Jr"],
    commands: ["kahlua"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-02-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Kahlua is a rescue ferret of Snails House. He is a very chill ferret that is often used for new ferret introductions. He is also a reformed ear criminal.",
    lore: `Kahlua came to the rescue together with [[Mai Tai]], [[Mimosa]], [[Scotch]] and [[Whiskey]]. Due to their names, they are also known as the alcohol or Booze crew.
Kahlua, like [[Beans]], spent time in ear crime jail, with the two sharing a cell for a short period before getting separate accommodations. Eventually, Kahlua was returned to the general population group after proving he could be a good boy.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Kahlua typed "Need1iap".`,
    clips: [],
    merch: null,
  },
  kitty: {
    name: "Kitty",
    wikipage: "Kitty",
    aliases: [
      "Baseboard Roomba, Excitement Incarnate, Destroyer of Lambchops, La Creatura",
    ],
    commands: ["kitty"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-12-19",
    valhalla: "2025-11-19",
    playgroup: "valhalla",
    summary:
      "Kitty was a rescue ferret of Snails House. She was a sweet little old white ferret. She got really excited about food and enjoyed fighting lambchop toys .",
    lore: "Kitty came to the rescue on December 19th, 2024. Kitty had Lymphoma, and started Chemo on 1/17/2025. Kitty was also missing most of her tail due to a chordoma. Despite her condition, Kitty seemed happy, healthy and had been gaining weight during her time with the rescue.",
    clips: [],
    merch: null,
  },
  koda: {
    name: "Koda",
    wikipage: "Koda",
    aliases: [],
    commands: ["koda"],
    sex: null,
    birth: null,
    birthday: null,
    arrival: "2026-01-27",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Koda is a rescue ferret of Snail's House. He came to the rescue with his cagemate Sokka.",
    lore: "Koda is a rescue ferret of Snail's House. Koda came to the rescue in January 2026 with his cagemate Sokka. Koda and Sokka formed the playgroup: Soda.",
    clips: [],
    merch: null,
  },
  kylo: {
    name: "Kylo",
    wikipage: "Kylo",
    aliases: [],
    commands: ["kylo"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-04-07",
    valhalla: "2025-05-02",
    playgroup: "valhalla",
    summary:
      "Kylo was a rescue ferret of Snails House. He came to the rescue with his roommate [[Roxy]].",
    lore: "Kylo was surrendered to Snails House due to medical complications. He arrived at the rescue with [[Roxy]].",
    clips: [],
    merch: null,
  },
  kyo: {
    name: "Kyo",
    wikipage: "Kyo",
    aliases: ["Speedy bouncer"],
    commands: ["kyo"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-06-05",
    valhalla: null,
    playgroup: "kyosai",
    summary:
      "Kyo is a rescue ferret of Snails House. She is an all-white ferret. Kyo really enjoys her playtime with her friend [[Sai]].",
    lore: "Kyo came to the rescue together with [[Sai]]. During their first playtime(s), it was determined they didn't mesh well with the big group of gen pop, and instead preferring each other's company. They get ample time in the big play room, as well as being Shaye's gaming buddies in Shaye's office. Kyo often seems to have an endless amount of energy, often times seen running around long after [[Sai]] has found a place to sleep.",
    clips: [],
    merch: null,
  },
  latte: {
    name: "Latte",
    wikipage: "Latte",
    aliases: ["Hawk", "From DIM baby to fearful fighter"],
    commands: ["latte"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-12-01",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Latte is a rescue ferret of Snails House. He is super feisty and enjoys play fighting with many of the ferrets. He also enjoys stashing/playing with the biggest toys he can find.",
    lore: "Latte joined the rescue not long after [[Mocha]] as the second ferret with DIM. At first he could barely move but over time and with the proper treatment he got back the ability to move like the others. Now that he's feeling better, he really likes to rile up Mocha during playtime.",
    clips: [],
    merch: null,
  },
  loki: {
    name: "Loki",
    wikipage: "Loki",
    aliases: ["The Original"],
    commands: ["loki"],
    sex: "Female",
    birth: null,
    birthday: "06-19",
    arrival: "2019-07-31",
    valhalla: "2025-09-11",
    playgroup: "valhalla",
    summary:
      "Loki was a rescue ferret of Snails House. She was one of the very first ferrets rescued. She was a sweet older lady who really enjoys stashing toys.",
    lore: `Loki was a breeder lab animal for the University of Washington. She came to the rescue with her fellow lab friend, [[Snails]] back in 2019. Loki's birthday is 2018/06/19.

Loki and [[Snails]] were the first two Ferrets Thor and Shaye rescued.

Loki loved to stash toys, regardless of their size.`,
    clips: [],
    merch: null,
  },
  louise: {
    name: "Louise",
    wikipage: "Louise",
    aliases: [],
    commands: ["louise"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-05-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Louise is a rescue ferret of Snails House. She came to the rescue with her sister, [[Thelma]]. She also enjoys climbing both her caretakers and a lot of the toys during playtime.",
    lore: `Louise joined the rescue together with her sister, [[Thelma]]. They came to the rescue as surrenders from the state of California.

For fun, Shaye allows the ferrets to impart wisdom upon the community. Louise typed "B see" and "9un".`,
    clips: [],
    merch: null,
  },
  lucas: {
    name: "Lucas",
    wikipage: "Lucas",
    aliases: [],
    commands: ["lucas", "luca"],
    sex: "Male",
    birth: "2019-12-08",
    birthday: "12-08",
    arrival: "2025-09-27",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Lucas is a rescue ferret of Snails House. He came from a loving home, where he lost his friends to age. He enjoys playtime with his fellow oldies.",
    lore: "Lucas came to the rescue from a loving home. His playmates had passed, and the owner wanted him to have ferret friends so he wouldn't be lonely. He is sweet and playfull.",
    clips: [],
    merch: null,
  },
  lucky: {
    name: "Lucky",
    wikipage: "Lucky",
    aliases: [],
    commands: ["lucky"],
    sex: "Male",
    birth: "2022-12-21",
    birthday: "12-21",
    arrival: "2023-07-07",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Lucky is a rescue ferret of Snails House. He is super playful, and he loves play fighting with everyone (even [[Henry]])! He thoroughly enjoys digging in snow. The vacuum is his ultimate nemesis.",
    lore: `Lucky was surrendered to the rescue by a pet store, along with his fellow cage mates [[Pickle]] and [[Spud]] because the store was opting out of selling ferrets. 

For fun, Shaye allows the ferrets to impart wisdom upon the community. Lucky typed "lin l0llll".`,
    clips: [],
    merch: null,
  },
  lulu: {
    name: "Lulu",
    wikipage: "Lulu",
    aliases: [],
    commands: ["lulu"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-11-16",
    valhalla: null,
    playgroup: "luno",
    summary:
      "Lulu is a rescue ferret of Snail's House. Lulu joined the rescue with [[Noodle]].",
    lore: "Lulu came with [[Noodle]] from a loving home who could no longer take care of them.",
    clips: [],
    merch: null,
  },
  luna: {
    name: "Luna",
    wikipage: "Luna",
    aliases: [],
    commands: ["luna"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-09-15",
    valhalla: "2025-10-17",
    playgroup: "valhalla",
    summary:
      "Luna was a rescue ferret of Snails House. She frequently enjoyed the rice box and was a total sweetheart who enjoyed snuggling with all the ferrets, even [[Henry]]. While she came in with her cagemate [[Odin]], she went on to reside with the oldies.",
    lore: "Luna arrived by a local surrender at 7 years old with fellow cagemate [[Odin]]. She sometimes liked to have sleepovers in the babies cage.",
    clips: [],
    merch: null,
  },
  maitai: {
    name: "Mai Tai",
    wikipage: "Mai_Tai",
    aliases: [],
    commands: ["maitai"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-02-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Mai Tai is a rescue ferret of Snails House. She is very playful with her fellow friends. She loves snuggling and playing with her human caretakers. She is a champagne-colored ferret with red eyes.",
    lore: "Mai Tai came to the rescue together with [[Kahlua]], [[Mimosa]], [[Scotch]] and [[Whiskey]]. Due to their names, they are also known as the alcohol crew.",
    clips: [],
    merch: null,
  },
  maisy: {
    name: "Maisy",
    wikipage: "Maisy",
    aliases: ["Business Lady, Serial Stasher"],
    commands: ["maisy"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-03-04",
    valhalla: null,
    playgroup: "m",
    summary:
      "Maisy is a rescue ferret of Snails House. She loves to stash all the toys! She came to the rescue with behavioral issues.",
    lore: `Maisy was surrendered by a pet store because she was biting the attendants. After about two months of training, she is now a nice little lady.

When she was first introduced to the business, she did not mesh well with a few of the youngest ferrets and lived alone for a bit. After [[Big Mike]] cleared quarantine, the two of them became the best of buddies. After a while, [[Milo]] was then added to their playgroup, transforming M&M to M3.

Maisy is a HUGE serial stasher of toys, and loves to chase her friends through the tubes.`,
    clips: [],
    merch: null,
  },
  max: {
    name: "Max",
    wikipage: "Max",
    aliases: ["Punk Rocker"],
    commands: ["max"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-09-12",
    valhalla: "2023-12-26",
    playgroup: "valhalla",
    summary: "Max was a rescue ferret of Snails House.",
    lore: `Max was surrendered to Shaye through their work clinic. His owner couldn't manage medication around their schooling schedule, so the rescue took him in, giving him an extra 5-6 months of life. * Max is a great example of surrendering a pet for the pet's best interest.
Even at an older age, he loved playing with the other ferrets
At about the age of 10, his body started to fail him, so he had to be let go.`,
    clips: [],
    merch: null,
  },
  milo: {
    name: "Milo",
    wikipage: "Milo",
    aliases: ["Miloš"],
    commands: ["milo"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-06-04",
    valhalla: null,
    playgroup: "m",
    summary:
      "Milo is a rescue ferret of Snails House. He came to the rescue due to serious behavioral issues. After months of rehabilitation, he loves bouncing around the playroom with his buddies.",
    lore: "Milo was originally surrendered from a pet store due to behavioral issues. Shaye spent lots of time rehabilitating these issues so that he can have a good life with the rest of the rescue and workers.",
    clips: [],
    merch: null,
  },
  mimosa: {
    name: "Mimosa",
    wikipage: "Mimosa",
    aliases: ["Mimi"],
    commands: ["mimosa"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-02-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Mimosa is a rescue ferret of Snails House. She is super playful with the other ferrets and enjoys noseballing the circular ball toy. She is classified as a champagne-colored ferret.",
    lore: "Mimosa came to the rescue together with [[Kahlua]], [[Mai Tai]], [[Scotch]] and [[Whiskey]]. Due to their names, they are also known as the alcohol crew.",
    clips: [],
    merch: null,
  },
  mishka: {
    name: "Mishka",
    wikipage: "Mishka",
    aliases: ["Toy hoarder"],
    commands: ["mishka"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-04-28",
    valhalla: "2025-09-14",
    playgroup: "valhalla",
    summary:
      "Mishka was a rescue ferret of Snails House. She was super energetic and loved to play with other ferrets. She also really enjoyed stashing toys.",
    lore: "Mishka was surrendered by a loving family at about 2 years old. She was spunky, liked to bite, and had a big personality.",
    clips: [],
    merch: null,
  },
  mistoffelees: {
    name: "Mistoffelees",
    wikipage: "Mistoffelees",
    aliases: ["Misto, Destroyer of food bowls, Enjoyer of floor kibble"],
    commands: ["mistoffelees", "mistoffelee"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-06-16",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Mistoffelees is a rescue ferret of Snails House. He came here with his roommate, [[Demeter]]. He enjoys making floor kibble by unscrewing the food dish. He has a unique face mask and four white paws.",
    lore: "Mistoffelees joined the rescue together with [[Demeter]]. They were surrendered because the owners felt they could no longer provide adequate care.",
    clips: [],
    merch: null,
  },
  mocha: {
    name: "Mocha",
    wikipage: "Mocha",
    aliases: [
      "Michael",
      "Mochael",
      "Ninja, Stealthmaster, Chonkzilla, Fluffiest of them all, Lt Dan",
    ],
    commands: ["mocha"],
    sex: "Male",
    birth: "2022-12-25",
    birthday: "12-25",
    arrival: "2023-11-03",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Mocha is a rescue ferret of Snails House. He's one of the business's most flexible and chill ferrets because he can be out with the oldies and the rambunctious babies. His stealth skills have far surpassed everyone in the rescue.",
    lore: `Mocha is currently one of the largest ferrets at Snails House 

While Mocha primarily bunks with genpop, he will visit his oldie friends from time to time for a sleepover due to his calm personality. He primarily sleeps with genpop, acting as a pillow for the cuddle puddles that form. During playtimes, Mocha frequently sleeps in various parts of the room. However, he tends to be active and play with the younger ferret groups when they're out at the same time. One of his frequent playtime tactics is to crawl into a tube and stop in the middle or the ends of it, then attempt to defend the path and block other ferrets from getting in.  Chat in the stream and discord have taken to calling this tunnel jousting or tunnel wars.

Mocha recently won a photo ferret calendar contest. He featured as the cover photo to of the r/ferrets, (found on Discord and reddit), 4th Edition Calendar. The proceeds of this calendar reportedly went to a ferret shelter in need. Love to all ferrets.`,
    clips: [],
    merch: null,
  },
  moose: {
    name: "Moose",
    wikipage: "Moose",
    aliases: [],
    commands: ["moose"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-02-26",
    valhalla: null,
    playgroup: "pms",
    summary:
      "Moose is a rescue ferret of Snails House. He enjoys the ball pit and loves to playfight with his friends, [[Salt]] and [[Pepper]].",
    lore: "Moose is a part of the 5 ferrets who were found abandoned in an unlocked shed by the Humane Society. They then reached out to the rescue for assistance. Moose came to the rescue with [[Badger]], [[Peepo]], [[Pepper]], and [[Salt]]",
    clips: [],
    merch: null,
  },
  mouse: {
    name: "Mouse",
    wikipage: "Mouse",
    aliases: ["Banshee Queen Mouse - Enjoyer of uppies, Loves to fly"],
    commands: ["mouse"],
    sex: "Female",
    birth: null,
    birthday: "04-01",
    arrival: "2023-04-28",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Mouse is a rescue ferret of Snails House. She has a rarer all-white coat pattern. Her favorite thing is uppies from the human caretakers, and she is the acting Queen of the business.",
    lore: `Mouse was surrendered to the rescue by her previous owner because of "behavioral issues". She is, as we call it, a "Waardy", (further explained below). She is, as the original ferretposting post said, "Deaf as a doornail". 

Thor is Mouse's favorite, and Thor has admitted that Mouse is his favorite.   

For fun, Shaye allows the ferrets to impart wisdom upon the community. Mouse typed "MLG" and "Phr60 CD or was rt t gn bkir".`,
    clips: [],
    merch: null,
  },
  moxie: {
    name: "Moxie",
    wikipage: "Moxie",
    aliases: ["Cuddle bug"],
    commands: ["moxie"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-01-05",
    valhalla: "2025-10-08",
    playgroup: "valhalla",
    summary:
      "Moxie was a rescue ferret of Snails House. She was a low key and chill oldie. She had a bottle brush tail.",
    lore: `After the passing of her crewmate, [[Bandit]], she was frequently seen with [[Eddie]]. (Per Shaye during playtime).
She had also taken a liking to [[Henry]] and loved being his cuddle buddy.

Moxie had a blood sugar crash and the community watching the stream helped her by alerting the caretakers.`,
    clips: [],
    merch: null,
  },
  nabooru: {
    name: "Nabooru",
    wikipage: "Nabooru",
    aliases: [],
    commands: ["nabooru"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Nabooru is a ferret of Snails House.",
    lore: "Nabooru joined the rescue with [[Zelda]], [[Darunia]], [[Saria]], [[Ruto]], [[Impa]], and [[Rauru]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  nacho: {
    name: "Nacho",
    wikipage: "Nacho",
    aliases: [],
    commands: ["nacho"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-04-17",
    valhalla: null,
    playgroup: "vons",
    summary:
      "Nacho is a rescue ferret of Snails House. He came to the rescue with his sister [[Salsa]] and enjoys playing with his friends [[Vincent]] and [[Onion]].",
    lore: "Nacho came to the rescue with his sister [[Salsa]]. They were surrendered by their owners to the rescue.",
    clips: [],
    merch: null,
  },
  nameko: {
    name: "Nameko",
    wikipage: "Nameko",
    aliases: ["Koko"],
    commands: ["nameko"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-10-25",
    valhalla: null,
    playgroup: "k",
    summary:
      "Nameko is a ferret of Snails House. She joined together with [[Enoki]].",
    lore: 'Nameko is a very chatty lady and dooks quite a lot. Being very curious, she likes to climb and explore everywhere she can. Nameko and Enoki\'s names were inspired by mushrooms.  Commonly and lovingly referred to by chat as "Boots with the Fur" because upon entry, she is bare except for her feet, neck, and head.',
    clips: [],
    merch: null,
  },
  nemo: {
    name: "Nemo",
    wikipage: "Nemo",
    aliases: [],
    commands: ["nemo"],
    sex: "Male",
    birth: "2025-08-30",
    birthday: "08-30",
    arrival: "2025-11-29",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Nemo is a rescue ferret of Snail's House. He is a spunky, fast, rambunctious little guy who loves playtime. He came to the rescue as a medical surrender.",
    lore: `Nemo came to Snails House at 2 months old after being found at a pet store with an injury. With the support and resources of the rescue, Nemo was able to receive life saving treatment, ultimately resulting in amputation.

Now a three legged ferret, he isn't letting his missing limb slow him down. He's a wild and rambunctious baby who loves playtime, especially adventuring through tubes, and rough-and-tumble sessions with pals like [[Pickle]] and [[Snowberry]]. His bold energy and fearless spirit already makes him a beloved member of the rescue.`,
    clips: [],
    merch: null,
  },
  noodle: {
    name: "Noodle",
    wikipage: "Noodle",
    aliases: [],
    commands: ["noodle"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-11-16",
    valhalla: null,
    playgroup: "luno",
    summary:
      "Noodle is a rescue ferret of Snail's House. Noodle joined the rescue with [[Lulu]].",
    lore: "Noodle came with [[Lulu]] from a loving home who could no longer take care of them.",
    clips: [],
    merch: null,
  },
  odin: {
    name: "Odin",
    wikipage: "Odin",
    aliases: ["Odie"],
    commands: ["odin"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-09-15",
    valhalla: "2026-02-09",
    playgroup: "valhalla",
    summary:
      "Odin is a rescue ferret of Snails House. He is a grumpy old guy who enjoys the quiet side of life during playtime. He came to the rescue with his cagemate [[Luna]].",
    lore: "Odin arrived as a local surrender at 7 years old with fellow cagemate [[Luna]].",
    clips: [],
    merch: null,
  },
  onion: {
    name: "Onion",
    wikipage: "Onion",
    aliases: ["Escape artist"],
    commands: ["onion"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2022-11-02",
    valhalla: null,
    playgroup: "vons",
    summary:
      "Onion is a ferret of Snails House. Onion was found on a rural road near where Thor and Shaye live by their neighbors. Their neighbors contacted them, and she has been safe in Snails House ever since.",
    lore: `She is best known for her escape attempts. She often tests the gates and boundaries, and often, she finds ways over them. 
Onion is known for her high intelligence, she has managed to escape from the enclosed area on many occasions. Onion will not be contained! Even as a young ferret, she managed to escape her actual cage/enclosure through slats under the bottom pan.

When Onion first came to the rescue, she was obsessed and imprinted on [[Beans]]. This eventually changed due to Beans' ear crimes, and now she has playtime with [[Vincent|Vinny]], [[Nacho]], and [[Salsa]].`,
    clips: [],
    merch: null,
  },
  peanut: {
    name: "Peanut",
    wikipage: "Peanut",
    aliases: ["Duracell battery included - Meanut"],
    commands: ["peanut"],
    sex: "Female",
    birth: "2024-04-13",
    birthday: "04-13",
    arrival: "2024-08-03",
    valhalla: null,
    playgroup: "genpop",
    summary:
      'Peanut is a rescue ferret of Snails House. She came to the rescue with her siblings [[Cashew]] and [[Hazelnut]]. She is known for having a heart shaped white blaze on her head and lots of energy. She truly enjoys chasing her "Uncle" [[Beans]] during playtime.',
    lore: 'Peanut was adopted from a pet store with [[Cashew]] and [[Hazelnut]] as part of the "Nut Gang".  Peanut has Waardenburg Syndrome   causing her to be partially deaf, as well as many behavioral issues. She was sold and returned multiple times due to these behavioral issues before the rescue acquired her.',
    clips: [],
    merch: null,
  },
  peanut2: {
    name: "Peanut 2",
    wikipage: "Peanut_2",
    aliases: ["Peacenut, Peanutbutter"],
    commands: ["peanut2"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-03-09",
    valhalla: "2025-09-12",
    playgroup: "valhalla",
    summary:
      "Peanut 2 was a rescue ferret of Snails House. She came to the rescue with her cagemate [[Bagel]] and really enjoyed her company. She was an older and very chill ferret who really enjoyed snuggles.",
    lore: `Peanut 2 came to the rescue together with [[Bagel]]. They were surrendered by loving owners due to age and existing health conditions.

She came to the rescue with her favourite toy rabbit and loved stashing it not very well all around the room.`,
    clips: [],
    merch: null,
  },
  peepo: {
    name: "Peepo",
    wikipage: "Peepo",
    aliases: ["Peep - Half the tail, double the wiggles"],
    commands: ["peepo"],
    sex: "Female",
    birth: null,
    birthday: "02-26",
    arrival: "2024-02-26",
    valhalla: "2025-10-31",
    playgroup: "valhalla",
    summary:
      "Peepo is a rescue ferret of Snails House. She is a sweet older lady who came to the rescue with [[Badger]], [[Moose]], [[Pepper]], and [[Salt]]. She enjoyed finding hiding spots in the playroom to hide from the caretakers. She had a shorter tail and was small size.",
    lore: "Peepo is a part of the 5 ferrets who were found abandoned in an unlocked shed by the Humane Society. They then reached out to the rescue for assistance. Peepo came to the rescue with [[Badger]],[[Moose]], [[Pepper]], and [[Salt]]",
    clips: [],
    merch: null,
  },
  pepper: {
    name: "Pepper",
    wikipage: "Pepper",
    aliases: ["Noseball champion"],
    commands: ["pepper"],
    sex: "Female",
    birth: null,
    birthday: "02-26",
    arrival: "2024-02-26",
    valhalla: null,
    playgroup: "pms",
    summary:
      "Pepper is a rescue ferret of Snails House. She came to the rescue with [[Badger]], [[Moose]], [[Peepo]], and [[Salt]]. She is a spunky ferret who enjoys playing noseball and loves doting on her human caretakers.",
    lore: "Pepper is a part of the 5 ferrets who were found abandoned in an unlocked shed by the Humane Society. They then reached out to the rescue for assistance. Pepper came to the rescue with [[Badger]], [[Moose]], [[Peepo]], and [[Salt]].",
    clips: [],
    merch: null,
  },
  pepper2: {
    name: "Pepper 2",
    wikipage: "Pepper_2",
    aliases: ["Pepperoni"],
    commands: ["pepper2"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-10-20",
    valhalla: "2025-11-01",
    playgroup: "valhalla",
    summary:
      "Pepper 2 was a rescue ferret of Snails House. He came from a loving home [who could no longer care for him] with his mates [[Skye]], [[Snowball]] and [[Salt 2]].",
    lore: `Pepper 2 joined the rescue together with [[Skye]], [[Snowball]] and [[Salt 2]]. 

After the passing of some of his fellow cagemates, he had been spending time with the oldies playgroup and enjoyed [[Peanut 2]] and [[Bagel]]'s company.`,
    clips: [],
    merch: null,
  },
  pickle: {
    name: "Pickle",
    wikipage: "Pickle",
    aliases: ["Chaos incarnate, Water bongo"],
    commands: ["pickle"],
    sex: "Male",
    birth: null,
    birthday: "04-03",
    arrival: "2023-08-07",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Pickle is a rescue ferret of Snails House. He is a super playful ferret of the babies and loves wardancing with everyone. He is the origin story for the yarrBongo and yarrGrass emotes.",
    lore: `Pickle was surrendered to the rescue by a pet store,  along with his bonded friend [[Spud]] and fellow cage mate [[Lucky]] because the store was opting out of selling ferrets. He has Waardenburg and is completely deaf. Waardenburg syndrome can cause deafness and behavioral issues in ferrets. Cage mate ferrets can develop similar behavioral issues due to this style of play within their cage. 

For fun, Shaye allows the ferrets to impart wisdom upon the community. Pickle typed "3bf", and "Zfa".`,
    clips: [],
    merch: null,
  },
  rauru: {
    name: "Rauru",
    wikipage: "Rauru",
    aliases: [],
    commands: ["rauru"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Rauru is a ferret of Snails House.",
    lore: "Rauru joined the rescue with [[Nabooru]], [[Darunia]], [[Saria]], [[Ruto]], [[Impa]], and [[Zelda]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  rose: {
    name: "Rose",
    wikipage: "Rose",
    aliases: [],
    commands: ["rose"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-01-07",
    valhalla: "2024-01-14",
    playgroup: "valhalla",
    summary: "Rose was a rescue ferret of Snails House.",
    lore: `Rose was one of the saddest cases the rescue had to deal with.


TRIGGER WARNINGS: Medical procedures and death


https://discord.com/channels/162034058736435201/1108087578617446541/1195577896891326545
The new ferret in the ICU made it through surgery.
The object is theorized to be a Macademia nut shell.
Attempting to digest this would explain the liver toxicity.
We still don't know for sure but this object is very plant/shell like in composition.
I will be sending it off to a lab to confirm after this is all over.

We have very few options here so we're taking what we can.
Lucky and Beans are about to be in-transit to do a blood transfusion.
Ferrets don't have blood types so there shouldn't be any complications.

Best chance she has.

https://discord.com/channels/162034058736435201/1108087578617446541/1195976293225865256
Good News: The objected swallowed by the little one does not appear to be toxic in nature.
Bad News: The old owners waiting 8 goddamn days to solve this caused her to go into Hepatic Acidosis.

This condition is caused by starvation and can easily lead to death.
She went into full Jaundice and her liver was highlighter yellow.
After the blood transfusion her Jaundice has mostly disappeared.
Right now we have her on fluids and are trying to manage the rest of her vitals.
It's basically whack a mole but the direction is positive so far.

Today was the "Do we keep going?" meeting and we opted to keep going.
Because she is so young (6 months) and the direction is positive it makes sense to do this.
We're going to have the meeting again in a few days and keep playing whack a mole until then.

https://discord.com/channels/162034058736435201/1108087578617446541/1196097535572459610
I'm sorry to say she did not make it.
Shortly before I ended the stream she went into cardiac arrested.
We made it there in time to say goodbye and nothing else.

We're going to be getting a necropsy to identify some of the causes that the treatment failed.
This should help the vets involved to treat cases like this better in the future.
It may not save her but it may save others.

We're also getting a pawprint in clay and a wooden urn for her and renamed her to Rose.
That way her name is not tied to the conditions or people that caused this preventable death.
When the new version of the ferret website is ready she will be in the memorial section.
Thankfully I was able to get a photo of her when she was brighter early in the day.

This is not the outcome we wanted but we did everything we could.
It is possible to commit no mistakes and still lose.
That is not a weakness. That is life.`,
    clips: [],
    merch: null,
  },
  rowan: {
    name: "Rowan",
    wikipage: "Rowan",
    aliases: [],
    commands: ["rowan"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-12-01",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Rowan is a rescue ferret of Snails House. Rowan came to the rescue with [[Ash]], [[Juniper]] and [[Rye]]",
    lore: "Rowan came with [[Ash]], [[Juniper]] and [[Rye]] from a very loving home in which life circumstances had unfortunately changed, so they came to Snails House.",
    clips: [],
    merch: null,
  },
  roxy: {
    name: "Roxy",
    wikipage: "Roxy",
    aliases: [],
    commands: ["roxy"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-04-07",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Roxy is a rescue ferret of Snails House. She came to the rescue with her roommate [[Kylo]].",
    lore: "Roxy came to the rescue as a roommate surrender with her friend [[Kylo]].",
    clips: [],
    merch: null,
  },
  rusty: {
    name: "Rusty",
    wikipage: "Rusty",
    aliases: ["Uncle Rusty"],
    commands: ["rusty"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-06-06",
    valhalla: null,
    playgroup: "rb",
    summary:
      "Rusty is a rescue ferret of Snails House. He is a spirited oldie who enjoys playing with others and loves stick chew treats.",
    lore: "Rusty was alone and surrendered from the same owners as [[Mouse]]. While he's an oldie, he is still quite spirited, playful, and can tough it with some young ferrets, as seen below in clips and photos.",
    clips: [],
    merch: null,
  },
  ruto: {
    name: "Ruto",
    wikipage: "Ruto",
    aliases: [],
    commands: ["ruto"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Ruto is a ferret of Snails House.",
    lore: "Ruto joined the rescue with [[Nabooru]], [[Darunia]], [[Saria]], [[Zelda]], [[Impa]], and [[Rauru]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  rye: {
    name: "Rye",
    wikipage: "Rye",
    aliases: [],
    commands: ["rye"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-12-01",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Rye is a rescue ferret of Snails House. Rye came to the rescue with [[Ash]], [[Rowan]] and [[Juniper]].",
    lore: "Rye came with [[Ash]], [[Rowan]] and [[Juniper]] from a very loving home in which life circumstances had unfortunately changed, so they came to Snails House.",
    clips: [],
    merch: null,
  },
  sai: {
    name: "Sai",
    wikipage: "Sai",
    aliases: [],
    commands: ["sai"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-06-05",
    valhalla: null,
    playgroup: "kyosai",
    summary:
      "Sai is a rescue ferret of Snails House. She came to the rescue with her cage mate [[Kyo]].",
    lore: "Sai came to the rescue together with [[Kyo]]. During their first playtime(s) it was determined they didn't mesh well with the big group of gen pop, preferring each other's company. They get ample time in the big play room, as well as being Shaye's gaming buddies in Shaye's office. Sai is more chill than Kyo, and normally, she falls asleep long before Kyo is out of energy.",
    clips: [],
    merch: null,
  },
  salsa: {
    name: "Salsa",
    wikipage: "Salsa",
    aliases: ["Thor nibbler"],
    commands: ["salsa"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2023-04-17",
    valhalla: null,
    playgroup: "vons",
    summary:
      "Salsa is a rescue ferret of Snails House. She came to the rescue with her brother, [[Nacho]] and enjoys playtime with [[Vincent|Vinny]] and [[Onion]].",
    lore: "Salsa came to the rescue with her brother, [[Nacho]]. They were surrendered by their owners to the rescue.",
    clips: [],
    merch: null,
  },
  salt: {
    name: "Salt",
    wikipage: "Salt",
    aliases: ["Saltine"],
    commands: ["salt"],
    sex: "Female",
    birth: null,
    birthday: "02-26",
    arrival: "2024-02-26",
    valhalla: null,
    playgroup: "pms",
    summary:
      "Salt is a rescue ferret of Snails House. She came from the local Humane Society with [[Badger]], [[Moose]], [[Peepo]], and [[Pepper]]. She is a very spirited and spicy ferret who loves to play with Moose and Pepper. She has an interesting coat pattern of an all-white coat with a black-tipped tail.",
    lore: `Salt is a part of the 5 ferrets who were found abandoned in an unlocked shed by the Humane Society. They then reached out to the rescue for assistance. Salt came to the rescue with [[Badger]], [[Moose]], [[Peepo]], and [[Pepper]].

Shaye has decided (in jest) that Salt's government name is actually Saltine, so at least then the color matches.`,
    clips: [],
    merch: null,
  },
  salt2: {
    name: "Salt 2",
    wikipage: "Salt_2",
    aliases: [],
    commands: ["salt2"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-10-20",
    valhalla: "2025-03-05",
    playgroup: "valhalla",
    summary: "Salt 2 was a rescue ferret of Snails House.",
    lore: "Salt 2 joined the rescue together with [[Skye]], [[Snowball]] and [[Pepper 2]]",
    clips: [],
    merch: null,
  },
  saria: {
    name: "Saria",
    wikipage: "Saria",
    aliases: [],
    commands: ["saria"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Saria is a ferret of Snails House.",
    lore: "Saria joined the rescue with [[Nabooru]], [[Darunia]], [[Zelda]], [[Ruto]], [[Impa]], and [[Rauru]]. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  scotch: {
    name: "Scotch",
    wikipage: "Scotch",
    aliases: [],
    commands: ["scotch"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-02-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Scotch is a rescue ferret of Snails House. He came from a loving home who could no longer care for him with his cagemates [[Kahlua]], [[Mai Tai]], [[Mimosa]] and [[Whiskey]]. He loves to be super rowdy and playful.",
    lore: "Scotch came to the rescue together with [[Kahlua]], [[Mai Tai]], [[Mimosa]] and [[Whiskey]]. Due to their names, they are also known as the alcohol crew.",
    clips: [],
    merch: null,
  },
  skye: {
    name: "Skye",
    wikipage: "Skye",
    aliases: ["Stasher of toys"],
    commands: ["skye"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-10-20",
    valhalla: "2025-01-28",
    playgroup: "valhalla",
    summary: "Skye was a rescue ferret of Snails House.",
    lore: "Skye joined the rescue together with [[Snowball]], [[Salt 2]] and [[Pepper 2]].",
    clips: [],
    merch: null,
  },
  snails: {
    name: "Snails",
    wikipage: "Snails",
    aliases: ["The First"],
    commands: ["snails", "snail"],
    sex: "Female",
    birth: null,
    birthday: "06-19",
    arrival: "2019-07-31",
    valhalla: "2023-04-22",
    playgroup: "valhalla",
    summary: "Snails was a rescue ferret of Snails House.",
    lore: "Snails was a breeder lab animal for the University of Washington and had 2 litters of kits. She came to the rescue with [[Loki]] back in 2019. Her birthday was June 19th, 2018. She is the original first ferret of the business, along with Loki, and is who the rescue is aptly named after. She passed of a heart condition in her sleep.",
    clips: [],
    merch: null,
  },
  snowball: {
    name: "Snowball",
    wikipage: "Snowball",
    aliases: [],
    commands: ["snowball"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-10-20",
    valhalla: "2025-04-05",
    playgroup: "valhalla",
    summary: "Snowball was a rescue ferret of Snails House.",
    lore: `Snowball joined the rescue together with [[Skye]], [[Salt 2]] and [[Pepper 2]].

Snowball was an Albino`,
    clips: [],
    merch: null,
  },
  snowberry: {
    name: "Snowberry",
    wikipage: "Snowberry",
    aliases: ["Snooby, Snowbear"],
    commands: ["snowberry"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2025-10-04",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Snowberry is a rescue ferret of Snails House. She came to the rescue with a leg injury. Despite this injury and ongoing recovery, she is walking better and has proved to be an avid explorer who enjoys making new friends.",
    lore: `Snowberry came to the rescue after being found at a remote park with a leg injury. She was found by a concerned couple, who also gave her the name she now carries. Upon examination by the vet, it was determined that her leg was fine, but the right side of her pelvis had suffered a compound fracture. The cause of the fracture is unknown.
She was prescribed 6-8 weeks of rest and pain management, and is making good strides in her recovery. She's very active and loves to explore the big room. She also seems very fond of [[Henry]] and [[Teep]]. She recently has been spotted cuddling with Lucas, and enjoys time within the Oldies group. Cheese and Jaz are her main snuggle buddies.`,
    clips: [],
    merch: null,
  },
  sokka: {
    name: "Sokka",
    wikipage: "Sokka",
    aliases: [],
    commands: ["sokka"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-01-27",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Sokka is a rescue ferret of Snail's House. He came to the rescue with his cagemate Koda.",
    lore: "Sokka is a rescue ferret of Snail's House. Sokka came to the rescue in January 2026 with his cagemate Koda. Sokka and Koda formed the playgroup: Soda.",
    clips: [],
    merch: null,
  },
  spud: {
    name: "Spud",
    wikipage: "Spud",
    aliases: ["Pickle's snugglebuddy"],
    commands: ["spud"],
    sex: "Male",
    birth: null,
    birthday: "04-03",
    arrival: "2023-08-07",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Spud is a rescue ferret of Snails House. He came to the rescue with his bonded friend [[Pickle]] and fellow cage mate [[Lucky]]. He loves to wrestle with Pickle, who loves him too much to fight back.",
    lore: "Spud was surrendered to the rescue by a pet store along with his bonded friend [[Pickle]] and fellow cage mate [[Lucky]] because the store was opting out of selling ferrets.",
    clips: [],
    merch: null,
  },
  stinky: {
    name: "Stinky",
    wikipage: "Stinky",
    aliases: [],
    commands: ["stinky"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2025-12-27",
    valhalla: null,
    playgroup: "fs",
    summary:
      "Stinky is a rescue ferret of Snails House. He is very sweet and came to the rescue with his friend [[Finch]].",
    lore: "Stinky came to Snails House with his cagemate [[Finch]] as medical surrenders, He is super sweet and enjoy cuddles.",
    clips: [],
    merch: null,
  },
  teep: {
    name: "Teep",
    wikipage: "Teep",
    aliases: ["Officer Teep"],
    commands: ["teep"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-03-30",
    valhalla: null,
    playgroup: "oldies",
    summary:
      "Teep is a rescue ferret of Snails House. She came to the rescue from a loving home with her cagemate [[Bruce]]. They were surrendered due to needed senior care the rescue could provide.",
    lore: `She enjoys enforcing the rules of the playroom, strongly. (Which is to have fun, of course!)

Teep affectionately earned the nickname "Officer Teep" when she chose to ride [[Henry]] like a horsey.`,
    clips: [],
    merch: null,
  },
  thelma: {
    name: "Thelma",
    wikipage: "Thelma",
    aliases: [],
    commands: ["thelma"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2024-05-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Thelma is a rescue ferret of Snails House. She came to the rescue with her sister [[Louise]]. She is super playful and loves to climb her human caretakers for snuggles.",
    lore: "Thelma joined the rescue together with her sister, [[Louise]]. They came to the rescue as surrenders from the state of California.",
    clips: [],
    merch: null,
  },
  toby: {
    name: "Toby",
    wikipage: "Toby",
    aliases: ["Grandson"],
    commands: ["toby"],
    sex: "Male",
    birth: "2024-04-13",
    birthday: "04-13",
    arrival: "2024-10-16",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Toby is a rescue ferret of Snails House. He was a solo medical surrender from a pet store.",
    lore: "He is very playful and loves to chase and be chased during playtime.",
    clips: [],
    merch: null,
  },
  torch: {
    name: "Torch",
    wikipage: "Torch",
    aliases: ["The brightest of flames"],
    commands: ["torch"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-08-25",
    valhalla: "2025-10-31",
    playgroup: "valhalla",
    summary:
      "Torch is a rescue ferret of Snails House. He was surrendered to the rescue from a loving home in Montana. While he was a super playful and bouncy ferret, he truly loved getting snuggles with his human caretakers.",
    lore: `Torch was adopted from Montana and looked like a healthy and well looked after ferret. 

Torch was 6 years old and per his previous owner: "Torch tried to take down a newborn baby goat once like an apex predator"`,
    clips: [],
    merch: null,
  },
  tortilla: {
    name: "Tortilla",
    wikipage: "Tortilla",
    aliases: ["Tito", "Climber of all things"],
    commands: ["tortilla"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-04-01",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Tortilla is a rescue ferret of Snails House. He was surrendered by a loving family as a solo ferret. He is a very clever ferret, who (when left to his own devices) will start climbing things for adventures!",
    lore: `Tortilla came to the rescue from a loving family as a surrender due to life circumstances beyond the owners control. Because he can sometimes get bored easily, he will often times try to climb things he shouldn't. He is always confused as to why his plans for adventure get foiled by the human caretakers.

He was the 7th ferret to join the rescue (yarr7).

For fun, Shaye allows the ferrets to impart wisdom upon the community. Tortilla typed "All 😍".`,
    clips: [],
    merch: null,
  },
  tucker: {
    name: "Tucker",
    wikipage: "Tucker",
    aliases: [],
    commands: ["tucker"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2026-02-18",
    valhalla: null,
    playgroup: "solo",
    summary:
      "Tucker is a rescue ferret of Snail's House. He came to the rescue with George.",
    lore: "Tucker came to the rescue in February 2026. Tucker joined the rescue with his cagemate George.",
    clips: [],
    merch: null,
  },
  vincent: {
    name: "Vincent",
    wikipage: "Vincent",
    aliases: ["Vinny", "The scrappy Fighter"],
    commands: ["vincent"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-11-19",
    valhalla: null,
    playgroup: "vons",
    summary:
      "Vincent is a rescue ferret of Snails House. He came to the rescue as an owner surrender due to medical needs. He now enjoys playtime with his friends [[Onion]], [[Nacho]], and [[Salsa]]. He is super active and playful with his friends. His coat pattern and eye color is a rarer combination of a white blaze on his head, white paws, and dark red eyes.",
    lore: "Vinny's origin story is quite grim and caused Thor to consume a pumpkin pie with his bare hands in the middle of the night at a USPS parking lot. * He is missing one of his ears, which caused Shaye to name him after Vincent Van Gogh. This is also because he is bonded to Shaye because of his Waardenburg Syndrome.",
    clips: [],
    merch: null,
  },
  whiskey: {
    name: "Whiskey",
    wikipage: "Whiskey",
    aliases: ["The perfect blend"],
    commands: ["whiskey"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2024-02-23",
    valhalla: null,
    playgroup: "genpop",
    summary:
      "Whiskey is a rescue ferret of Snails House. He came to the rescue with his friends [[Kahlua]], [[Mai Tai]], [[Mimosa]] and [[Scotch]]. He is a super active ferret who loves to play with toys and enjoys stashing them.",
    lore: `Came to the rescue together with [[Kahlua]], [[Mai Tai]], [[Mimosa]] and [[Scotch]] from a loving home. Their owner had to give them up due to life circumstances. Due to their names, they are also known as the alcohol crew.

For fun, Shaye allows the ferrets to impart wisdom upon the ccommunity. Whiskey typed "((o.o)".`,
    clips: [],
    merch: null,
  },
  zelda: {
    name: "Zelda",
    wikipage: "Zelda",
    aliases: [],
    commands: ["zelda"],
    sex: "Female",
    birth: null,
    birthday: null,
    arrival: "2026-01-20",
    valhalla: null,
    playgroup: "solo",
    summary: "Zelda is a ferret of Snails House.",
    lore: "Zelda joined the rescue with [[Nabooru]], [[Darunia]], [[Saria]], [[Ruto]], [[Impa]], and [[Rauru]]. She is the youngest of the group. This groups names were inspired by the Legend of Zelda: Ocarina of Time sages.",
    clips: [],
    merch: null,
  },
  zero: {
    name: "Zero",
    wikipage: "Zero",
    aliases: ["Hero", "Grandpa, Peepaw, huge cuddle bug, sleeps everywhere"],
    commands: ["zero"],
    sex: "Male",
    birth: null,
    birthday: null,
    arrival: "2023-06-07",
    valhalla: "2024-07-02",
    playgroup: "valhalla",
    summary: "Zero was a rescue ferret of Snails House.",
    lore: "Zero was originally surrendered because his owner was unable to financially pursue treatment for his tumors, adrenal disease and insulinoma.",
    clips: [],
    merch: null,
  },
} as const satisfies Record<string, Ferret>;

export type Ferrets = typeof ferrets;

export type FerretKey = keyof Ferrets;

const ferretKeys = Object.keys(ferrets) as FerretKey[];

export const isFerretKey = (str: string): str is FerretKey =>
  ferretKeys.includes(str as FerretKey);

export default ferrets;
